name: 本番デプロイ
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: "production"
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Node.jsのインストール
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: pnpmのインストール
        with:
          version: 8
          run_install: false
      - name: pnpm storeのパスを取得
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: pnpm storeのキャッシュ
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: パッケージのインストール
        run: pnpm install

      - name: Vercel CLIのインストール
        run: pnpm install -g vercel@latest
      - name: Vercelから本番環境用設定を取得
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: 本番用ビルド
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: 成果物を本番環境でデプロイ
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
